import enum

class UserRole(str, enum.Enum):
    STUDENT = "STUDENT"
    PARENT = "PARENT"
    ACCOUNTS_OFFICER = "ACCOUNTS_OFFICER"
    ADMIN = "ADMIN"
    MANAGEMENT = "MANAGEMENT"
    FINANCE_APPROVER = "FINANCE_APPROVER"
    SYSTEM_ADMIN = "SYSTEM_ADMIN"

class FeeHeadType(str, enum.Enum):
    TUITION = "TUITION"
    EXAMINATION = "EXAMINATION"
    HOSTEL = "HOSTEL"
    TRANSPORT = "TRANSPORT"
    LABORATORY = "LABORATORY"
    LIBRARY = "LIBRARY"
    CAUTION_DEPOSIT = "CAUTION_DEPOSIT"
    ONE_TIME_CHARGES = "ONE_TIME_CHARGES"
    OTHER = "OTHER"

class FeeStructureStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    SUPERSEDED = "SUPERSEDED"
    ARCHIVED = "ARCHIVED"

class FeeDemandStatus(str, enum.Enum):
    PENDING = "PENDING"
    PARTIALLY_PAID = "PARTIALLY_PAID"
    PAID = "PAID"
    OVERDUE = "OVERDUE"
    CANCELLED = "CANCELLED"

class PaymentChannel(str, enum.Enum):
    ONLINE_GATEWAY = "ONLINE_GATEWAY"
    BANK_TRANSFER = "BANK_TRANSFER"
    COUNTER = "COUNTER"
    CASH = "CASH"
    UPI = "UPI"
    NEFT = "NEFT"
    RTGS = "RTGS"
    CARD = "CARD"
    CHEQUE = "CHEQUE"
    ONLINE = "ONLINE"

class PaymentStatus(str, enum.Enum):
    PENDING = "PENDING"
    RECEIVED = "RECEIVED"
    RECONCILED = "RECONCILED"
    PARTIALLY_RECONCILED = "PARTIALLY_RECONCILED"
    MISMATCH = "MISMATCH"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    REVERSED = "REVERSED"

class ReconciliationStatus(str, enum.Enum):
    UNMATCHED = "UNMATCHED"
    MATCHED = "MATCHED"
    UNRECONCILED = "UNRECONCILED"
    MISMATCH = "MISMATCH"
    EXCEPTION = "EXCEPTION"
    MANUALLY_RESOLVED = "MANUALLY_RESOLVED"

class MismatchCategory(str, enum.Enum):
    AMOUNT_MISMATCH = "AMOUNT_MISMATCH"
    MISSING_TRANSACTION = "MISSING_TRANSACTION"
    DUPLICATE_TRANSACTION = "DUPLICATE_TRANSACTION"
    WRONG_STUDENT = "WRONG_STUDENT"
    WRONG_FEE_HEAD = "WRONG_FEE_HEAD"
    DATE_MISMATCH = "DATE_MISMATCH"
    ACCOUNTING_MISMATCH = "ACCOUNTING_MISMATCH"

class RefundStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    PROCESSED = "PROCESSED"
    CANCELLED = "CANCELLED"

class ApprovalStatus(str, enum.Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"

class ApprovalType(str, enum.Enum):
    REFUND = "REFUND"
    BALANCE_ADJUSTMENT = "BALANCE_ADJUSTMENT"
    FEE_WAIVER = "FEE_WAIVER"
    PAYMENT_REASSIGNMENT = "PAYMENT_REASSIGNMENT"
    MANUAL_CORRECTION = "MANUAL_CORRECTION"
    EXAM_PERMISSION = "EXAM_PERMISSION"

class AuditAction(str, enum.Enum):
    READ = "READ"
    CREATE = "CREATE"
    UPDATE = "UPDATE"
    DELETE = "DELETE"
    APPROVE = "APPROVE"
    REJECT = "REJECT"
    RECONCILE = "RECONCILE"
    ALLOCATE = "ALLOCATE"
    CALCULATE = "CALCULATE"
    REVERSE = "REVERSE"
    MATCH = "MATCH"
