"""
seed_students_data.py
---------------------
200 realistic Indian student profiles across 11 academic degree programs.
Includes diverse modes of admission:
  1. EAMCET (State Convener Quota)
  2. VSAT (Vignan Scholastic Aptitude Test)
  3. JEE_MAINS (National Entrance with Percentile-Tiered Scholarships)
  4. RESERVED_CATEGORY (Lower Caste / Reserved Category - SC/ST/OBC Welfare Scheme)
  5. SPECIAL_STATE (Special State Status Quota - North-East / J&K / Special Category States)
  6. MANAGEMENT (Institutional Direct Quota)

Each tuple format:
  (roll_no, full_name, email_prefix, program_code, category_code,
   admission_route_code, semester, parent_email, parent_name, entrance_metric)
"""

# fmt: off
STUDENT_PROFILES = [
    # ── B.Tech CSE (40 students) ──────────────────────────────────────────────
    ("STU1001","Aravind Kumar",       "aravind.k",    "BTECH-CSE", "GEN",  "JEE_MAINS",         1, "parent.aravind@gmail.com","Sundaram Kumar", 96.8),
    ("STU1002","Priya Sharma",        "priya.s",      "BTECH-CSE", "GEN",  "JEE_MAINS",         1, "parent.priya@gmail.com",  "Ramesh Sharma",  95.4),
    ("STU1003","Kiran Varma",         "kiran.v",      "BTECH-CSE", "OBC",  "VSAT",              3, None, None, 45),
    ("STU1004","Deepika Reddy",       "deepika.r",    "BTECH-CSE", "MGMT", "MANAGEMENT",        1, None, None, "Cat-B"),
    ("STU1005","Sneha Patel",         "sneha.p",      "BTECH-CSE", "GEN",  "EAMCET",            1, None, None, 3420),
    ("STU1006","Manoj Tiwari",        "manoj.t",      "BTECH-CSE", "SC",   "RESERVED_CATEGORY", 1, None, None, "SC Welfare"),
    ("STU1007","Anusha Rao",          "anusha.r",     "BTECH-CSE", "ST",   "RESERVED_CATEGORY", 1, None, None, "ST Tribal Welfare"),
    ("STU1008","Swati Deshmukh",      "swati.d",      "BTECH-CSE", "OBC",  "RESERVED_CATEGORY", 1, None, None, "OBC Concession"),
    ("STU1009","Divya Menon",         "divya.m",      "BTECH-CSE", "GEN",  "SPECIAL_STATE",     1, None, None, "Jammu & Kashmir"),
    ("STU1010","Meera Iyer",          "meera.i",      "BTECH-CSE", "GEN",  "JEE_MAINS",         1, None, None, 98.6),
    ("STU1011","Pooja Hegde",         "pooja.h",      "BTECH-CSE", "GEN",  "VSAT",              1, None, None, 82),
    ("STU1012","Gautam Reddy",        "gautam.r",     "BTECH-CSE", "GEN",  "EAMCET",            1, None, None, 4510),
    ("STU1013","Lakshmi Bai",         "lakshmi.b",    "BTECH-CSE", "OBC",  "EAMCET",            1, None, None, 8920),
    ("STU1014","Harini Venkat",       "harini.v",     "BTECH-CSE", "GEN",  "SPECIAL_STATE",     1, None, None, "Assam"),
    ("STU1015","Abhishek Nair",       "abhishek.n",   "BTECH-CSE", "GEN",  "JEE_MAINS",         2, None, None, 95.8),
    ("STU1016","Tarun Kumar",         "tarun.k",      "BTECH-CSE", "GEN",  "JEE_MAINS",         2, None, None, 92.4),
    ("STU1017","Varun Dhawan",        "varun.d",      "BTECH-CSE", "GEN",  "VSAT",              2, None, None, 140),
    ("STU1018","Alia Singh",          "alia.s",       "BTECH-CSE", "MGMT", "MANAGEMENT",        2, None, None, "Cat-B"),
    ("STU1019","Siddharth Rao",       "siddharth.r",  "BTECH-CSE", "GEN",  "JEE_MAINS",         3, None, None, 97.2),
    ("STU1020","Neha Joshi",          "neha.j",       "BTECH-CSE", "GEN",  "JEE_MAINS",         3, None, None, 95.1),
    ("STU1021","Rahul Verma",         "rahul.v",      "BTECH-CSE", "OBC",  "RESERVED_CATEGORY", 4, None, None, "OBC Concession"),
    ("STU1022","Pallavi Krishnan",    "pallavi.k",    "BTECH-CSE", "SC",   "RESERVED_CATEGORY", 4, None, None, "SC Welfare"),
    ("STU1023","Srikar Reddy",        "srikar.r",     "BTECH-CSE", "GEN",  "VSAT",              4, None, None, 210),
    ("STU1024","Revathi Subramaniam", "revathi.s",    "BTECH-CSE", "GEN",  "SPECIAL_STATE",     5, None, None, "Manipur"),
    ("STU1025","Aditya Sharma",       "aditya.s",     "BTECH-CSE", "GEN",  "JEE_MAINS",         5, None, None, 99.1),
    ("STU1026","Bhavana Reddy",       "bhavana.r",    "BTECH-CSE", "ST",   "RESERVED_CATEGORY", 5, None, None, "ST Tribal Welfare"),
    ("STU1027","Chandra Sekhar",      "chandra.s",    "BTECH-CSE", "GEN",  "EAMCET",            6, None, None, 6720),
    ("STU1028","Durga Prasad",        "durga.p",      "BTECH-CSE", "OBC",  "EAMCET",            6, None, None, 9150),
    ("STU1029","Eswar Reddy",         "eswar.r",      "BTECH-CSE", "GEN",  "VSAT",              7, None, None, 380),
    ("STU1030","Fathima Begum",       "fathima.b",    "BTECH-CSE", "OBC",  "EAMCET",            7, None, None, 11200),
    ("STU1031","Ganesh Kumar",        "ganesh.k",     "BTECH-CSE", "GEN",  "JEE_MAINS",         7, None, None, 88.5),
    ("STU1032","Hema Malini",         "hema.m",       "BTECH-CSE", "SC",   "RESERVED_CATEGORY", 8, None, None, "SC Welfare"),
    ("STU1033","Indra Priya",         "indra.p",      "BTECH-CSE", "GEN",  "JEE_MAINS",         8, None, None, 96.2),
    ("STU1034","Jaya Prakash",        "jaya.p",       "BTECH-CSE", "MGMT", "MANAGEMENT",        8, None, None, "Cat-B"),
    ("STU1035","Karthikeyan N",       "karthik.n",    "BTECH-CSE", "GEN",  "EAMCET",            8, None, None, 5800),
    ("STU1036","Lalitha Devi",        "lalitha.d",    "BTECH-CSE", "OBC",  "SPECIAL_STATE",     6, None, None, "Sikkim"),
    ("STU1037","Mani Shankar",        "mani.s",       "BTECH-CSE", "GEN",  "EAMCET",            5, None, None, 7400),
    ("STU1038","Nandini Rao",         "nandini.r",    "BTECH-CSE", "GEN",  "VSAT",              4, None, None, 95),
    ("STU1039","Om Prakash",          "om.p",         "BTECH-CSE", "SC",   "RESERVED_CATEGORY", 3, None, None, "SC Welfare"),
    ("STU1040","Pavithra Sriram",     "pavithra.s",   "BTECH-CSE", "GEN",  "JEE_MAINS",         2, None, None, 91.0),

    # ── B.Tech CSE-AI/ML (25 students) ───────────────────────────────────────
    ("STU1041","Qasim Ali",           "qasim.a",      "BTECH-CSE-AI", "GEN",  "JEE_MAINS",         1, None, None, 96.5),
    ("STU1042","Ramya Krishnaswamy",  "ramya.k",      "BTECH-CSE-AI", "GEN",  "VSAT",              1, None, None, 68),
    ("STU1043","Surya Prakash",       "surya.p",      "BTECH-CSE-AI", "OBC",  "RESERVED_CATEGORY", 1, None, None, "OBC Concession"),
    ("STU1044","Tejas Naidu",         "tejas.n",      "BTECH-CSE-AI", "GEN",  "JEE_MAINS",         1, None, None, 95.5),
    ("STU1045","Uma Devi",            "uma.d",        "BTECH-CSE-AI", "SC",   "RESERVED_CATEGORY", 1, None, None, "SC Welfare"),
    ("STU1046","Vignesh Rajan",       "vignesh.r",    "BTECH-CSE-AI", "GEN",  "EAMCET",            2, None, None, 3950),
    ("STU1047","Wasim Ahmed",         "wasim.a",      "BTECH-CSE-AI", "OBC",  "EAMCET",            2, None, None, 8400),
    ("STU1048","Yamini Lakshmi",      "yamini.l",     "BTECH-CSE-AI", "GEN",  "SPECIAL_STATE",     2, None, None, "Meghalaya"),
    ("STU1049","Zaheer Khan",         "zaheer.k",     "BTECH-CSE-AI", "GEN",  "JEE_MAINS",         2, None, None, 98.4),
    ("STU1050","Anjali Mishra",       "anjali.m",     "BTECH-CSE-AI", "GEN",  "VSAT",              2, None, None, 135),
    ("STU1051","Balaji Venkat",       "balaji.v",     "BTECH-CSE-AI", "GEN",  "EAMCET",            3, None, None, 4890),
    ("STU1052","Chandrika Patel",     "chandrika.p",  "BTECH-CSE-AI", "MGMT", "MANAGEMENT",        3, None, None, "Cat-B"),
    ("STU1053","Devendra Singh",      "devendra.s",   "BTECH-CSE-AI", "GEN",  "JEE_MAINS",         3, None, None, 93.6),
    ("STU1054","Eswari Devi",         "eswari.d",     "BTECH-CSE-AI", "SC",   "RESERVED_CATEGORY", 3, None, None, "SC Welfare"),
    ("STU1055","Firoz Khan",          "firoz.k",      "BTECH-CSE-AI", "OBC",  "EAMCET",            3, None, None, 9200),
    ("STU1056","Geetha Krishnan",     "geetha.k",     "BTECH-CSE-AI", "GEN",  "SPECIAL_STATE",     4, None, None, "Jammu & Kashmir"),
    ("STU1057","Harsha Vardhan",      "harsha.v",     "BTECH-CSE-AI", "GEN",  "JEE_MAINS",         4, None, None, 97.5),
    ("STU1058","Ishita Gupta",        "ishita.g",     "BTECH-CSE-AI", "GEN",  "VSAT",              4, None, None, 290),
    ("STU1059","Jagadish Reddy",      "jagadish.r",   "BTECH-CSE-AI", "MGMT", "MANAGEMENT",        4, None, None, "Cat-B"),
    ("STU1060","Kavitha Subramanian", "kavitha.s",    "BTECH-CSE-AI", "GEN",  "EAMCET",            4, None, None, 5600),
    ("STU1061","Lohith Gowda",        "lohith.g",     "BTECH-CSE-AI", "GEN",  "EAMCET",            1, None, None, 6100),
    ("STU1062","Madhuri Nair",        "madhuri.n",    "BTECH-CSE-AI", "OBC",  "RESERVED_CATEGORY", 1, None, None, "OBC Concession"),
    ("STU1063","Narendra Babu",       "narendra.b",   "BTECH-CSE-AI", "GEN",  "VSAT",              2, None, None, 88),
    ("STU1064","Oviya Raman",         "oviya.r",      "BTECH-CSE-AI", "SC",   "RESERVED_CATEGORY", 2, None, None, "SC Welfare"),
    ("STU1065","Prasanna Kumar",      "prasanna.k",   "BTECH-CSE-AI", "GEN",  "JEE_MAINS",         3, None, None, 86.4),

    # ── B.Tech ECE (25 students) ──────────────────────────────────────────────
    ("STU1066","Rohan Goud",          "rohan.goud",   "BTECH-ECE",    "GEN",  "JEE_MAINS",         1, None, None, 96.0),
    ("STU1067","Sneha Reddy",         "sneha.re",     "BTECH-ECE",    "GEN",  "VSAT",              1, None, None, 75),
    ("STU1068","Teja Varma",          "teja.v",       "BTECH-ECE",    "OBC",  "RESERVED_CATEGORY", 1, None, None, "OBC Concession"),
    ("STU1069","Usha Rani",           "usha.r",       "BTECH-ECE",    "SC",   "RESERVED_CATEGORY", 1, None, None, "SC Welfare"),
    ("STU1070","Vikas Sharma",        "vikas.s",      "BTECH-ECE",    "GEN",  "EAMCET",            1, None, None, 5100),
    ("STU1071","Kiran Raj",           "kiran.raj",    "BTECH-ECE",    "MGMT", "MANAGEMENT",        2, None, None, "Cat-B"),
    ("STU1072","Archana Devi",        "archana.d",    "BTECH-ECE",    "GEN",  "JEE_MAINS",         2, None, None, 95.2),
    ("STU1073","Bhaskar Rao",         "bhaskar.r",    "BTECH-ECE",    "GEN",  "SPECIAL_STATE",     2, None, None, "Assam"),
    ("STU1074","Chetan Anand",        "chetan.a",     "BTECH-ECE",    "OBC",  "EAMCET",            3, None, None, 8900),
    ("STU1075","Deeksha Pillai",      "deeksha.p",    "BTECH-ECE",    "GEN",  "VSAT",              3, None, None, 160),
    ("STU1076","Esha Mehta",          "esha.m",       "BTECH-ECE",    "GEN",  "JEE_MAINS",         4, None, None, 92.8),
    ("STU1077","Farhan Shaikh",       "farhan.s",     "BTECH-ECE",    "OBC",  "EAMCET",            4, None, None, 10400),
    ("STU1078","Gayatri Reddy",       "gayatri.r",    "BTECH-ECE",    "SC",   "RESERVED_CATEGORY", 5, None, None, "SC Welfare"),
    ("STU1079","Harish Babu",         "harish.b",     "BTECH-ECE",    "GEN",  "EAMCET",            5, None, None, 6800),
    ("STU1080","Indu Bala",           "indu.b",       "BTECH-ECE",    "GEN",  "SPECIAL_STATE",     6, None, None, "Ladakh"),
    ("STU1081","Jayendra Kumar",      "jayendra.k",   "BTECH-ECE",    "GEN",  "JEE_MAINS",         6, None, None, 97.1),
    ("STU1082","Kaveri Suresh",       "kaveri.s",     "BTECH-ECE",    "MGMT", "MANAGEMENT",        7, None, None, "Cat-B"),
    ("STU1083","Lokesh Sharma",       "lokesh.s",     "BTECH-ECE",    "GEN",  "EAMCET",            7, None, None, 7200),
    ("STU1084","Meenakshi Iyer",      "meenakshi.i",  "BTECH-ECE",    "OBC",  "RESERVED_CATEGORY", 8, None, None, "OBC Concession"),
    ("STU1085","Naresh Kumar",        "naresh.k",     "BTECH-ECE",    "GEN",  "VSAT",              8, None, None, 320),
    ("STU1086","Padma Rao",           "padma.r",      "BTECH-ECE",    "ST",   "RESERVED_CATEGORY", 3, None, None, "ST Tribal Welfare"),
    ("STU1087","Rajesh Nair",         "rajesh.n",     "BTECH-ECE",    "GEN",  "EAMCET",            4, None, None, 8100),
    ("STU1088","Saritha Pillai",      "saritha.p",    "BTECH-ECE",    "GEN",  "JEE_MAINS",         2, None, None, 95.7),
    ("STU1089","Thilak Raj",          "thilak.r",     "BTECH-ECE",    "OBC",  "EAMCET",            1, None, None, 9500),
    ("STU1090","Umesh Yadav",         "umesh.y",      "BTECH-ECE",    "GEN",  "EAMCET",            5, None, None, 8700),

    # ── B.Tech EEE (15 students) ──────────────────────────────────────────────
    ("STU1091","Vandana Sinha",       "vandana.s",    "BTECH-EEE",    "GEN",  "VSAT",              1, None, None, 98),
    ("STU1092","Waqar Ahmed",         "waqar.a",      "BTECH-EEE",    "OBC",  "RESERVED_CATEGORY", 1, None, None, "OBC Concession"),
    ("STU1093","Xavier D'Souza",      "xavier.d",     "BTECH-EEE",    "GEN",  "JEE_MAINS",         2, None, None, 96.1),
    ("STU1094","Yogesh Patil",        "yogesh.p",     "BTECH-EEE",    "GEN",  "EAMCET",            2, None, None, 6400),
    ("STU1095","Zara Siddiqui",       "zara.s",       "BTECH-EEE",    "OBC",  "EAMCET",            3, None, None, 9800),
    ("STU1096","Anand Krishnan",      "anand.k",      "BTECH-EEE",    "SC",   "RESERVED_CATEGORY", 3, None, None, "SC Welfare"),
    ("STU1097","Bharati Reddy",       "bharati.r",    "BTECH-EEE",    "GEN",  "SPECIAL_STATE",     4, None, None, "Nagaland"),
    ("STU1098","Chidambaram R",       "chidambaram.r","BTECH-EEE",    "GEN",  "JEE_MAINS",         4, None, None, 95.3),
    ("STU1099","Divyarani Patel",     "divyarani.p",  "BTECH-EEE",    "MGMT", "MANAGEMENT",        5, None, None, "Cat-B"),
    ("STU1100","Elamaran Pandian",    "elamaran.p",   "BTECH-EEE",    "GEN",  "EAMCET",            5, None, None, 7900),
    ("STU1101","Fozia Begum",         "fozia.b",      "BTECH-EEE",    "OBC",  "EAMCET",            6, None, None, 11400),
    ("STU1102","Ganpat Yadav",        "ganpat.y",     "BTECH-EEE",    "GEN",  "VSAT",              6, None, None, 280),
    ("STU1103","Haripriya Devi",      "haripriya.d",  "BTECH-EEE",    "SC",   "RESERVED_CATEGORY", 7, None, None, "SC Welfare"),
    ("STU1104","Iqbal Hussain",       "iqbal.h",      "BTECH-EEE",    "OBC",  "EAMCET",            7, None, None, 12600),
    ("STU1105","Jyothi Sai",          "jyothi.s",     "BTECH-EEE",    "GEN",  "JEE_MAINS",         8, None, None, 91.5),

    # ── B.Tech MECH (20 students) ─────────────────────────────────────────────
    ("STU1106","Rohit Nair",          "rohit.n",      "BTECH-MECH",   "GEN",  "JEE_MAINS",         5, None, None, 95.6),
    ("STU1107","Sanjeev Dutt",        "sanjeev.d",    "BTECH-MECH",   "MGMT", "MANAGEMENT",        1, None, None, "Cat-B"),
    ("STU1108","Navin Patnaik",       "navin.p",      "BTECH-MECH",   "GEN",  "VSAT",              1, None, None, 85),
    ("STU1109","Vikrant Singh",       "vikrant.s",    "BTECH-MECH",   "GEN",  "EAMCET",            3, None, None, 7100),
    ("STU1110","Siddhesh M",          "siddhesh.m",   "BTECH-MECH",   "GEN",  "SPECIAL_STATE",     1, None, None, "Manipur"),
    ("STU1111","Karan Kapoor",        "karan.k",      "BTECH-MECH",   "OBC",  "RESERVED_CATEGORY", 2, None, None, "OBC Concession"),
    ("STU1112","Arundhati P",         "arundhati.p",  "BTECH-MECH",   "OBC",  "EAMCET",            1, None, None, 9800),
    ("STU1113","Lavanya Gopal",       "lavanya.g",    "BTECH-MECH",   "GEN",  "JEE_MAINS",         3, None, None, 96.9),
    ("STU1114","Madan Mohan",         "madan.m",      "BTECH-MECH",   "GEN",  "EAMCET",            4, None, None, 8400),
    ("STU1115","Nirmal Singh",        "nirmal.s",     "BTECH-MECH",   "SC",   "RESERVED_CATEGORY", 5, None, None, "SC Welfare"),
    ("STU1116","Omkar Patil",         "omkar.p",      "BTECH-MECH",   "GEN",  "VSAT",              6, None, None, 190),
    ("STU1117","Pratima Shukla",      "pratima.s",    "BTECH-MECH",   "GEN",  "EAMCET",            7, None, None, 9200),
    ("STU1118","Raghavan Iyer",       "raghavan.i",   "BTECH-MECH",   "GEN",  "SPECIAL_STATE",     8, None, None, "Jammu & Kashmir"),
    ("STU1119","Shyam Sundar",        "shyam.s",      "BTECH-MECH",   "OBC",  "EAMCET",            6, None, None, 10800),
    ("STU1120","Tanvi Bhatt",         "tanvi.b",      "BTECH-MECH",   "GEN",  "JEE_MAINS",         5, None, None, 98.1),
    ("STU1121","Upendra Rao",         "upendra.r",    "BTECH-MECH",   "GEN",  "EAMCET",            4, None, None, 9600),
    ("STU1122","Veena Kumari",        "veena.k",      "BTECH-MECH",   "ST",   "RESERVED_CATEGORY", 3, None, None, "ST Tribal Welfare"),
    ("STU1123","Waseem Akhtar",       "waseem.a",     "BTECH-MECH",   "OBC",  "EAMCET",            2, None, None, 11500),
    ("STU1124","Yaswanth Reddy",      "yaswanth.r",   "BTECH-MECH",   "GEN",  "VSAT",              1, None, None, 420),
    ("STU1125","Zeena Francis",       "zeena.f",      "BTECH-MECH",   "MGMT", "MANAGEMENT",        2, None, None, "Cat-B"),

    # ── B.Tech CIVIL (15 students) ────────────────────────────────────────────
    ("STU1126","Ajay Devgn",          "ajay.d",       "BTECH-CIVIL",  "GEN",  "VSAT",              1, None, None, 92),
    ("STU1127","Bindiya Rathod",      "bindiya.r",    "BTECH-CIVIL",  "OBC",  "RESERVED_CATEGORY", 1, None, None, "OBC Concession"),
    ("STU1128","Charan Tej",          "charan.t",     "BTECH-CIVIL",  "GEN",  "JEE_MAINS",         2, None, None, 95.9),
    ("STU1129","Deepa Menon",         "deepa.m",      "BTECH-CIVIL",  "SC",   "RESERVED_CATEGORY", 3, None, None, "SC Welfare"),
    ("STU1130","Ekta Kapoor",         "ekta.k",       "BTECH-CIVIL",  "GEN",  "EAMCET",            4, None, None, 8200),
    ("STU1131","Farida Bano",         "farida.b",     "BTECH-CIVIL",  "OBC",  "EAMCET",            5, None, None, 10900),
    ("STU1132","Girish Kumar",        "girish.k",     "BTECH-CIVIL",  "GEN",  "SPECIAL_STATE",     6, None, None, "Assam"),
    ("STU1133","Himanshu Jain",       "himanshu.j",   "BTECH-CIVIL",  "GEN",  "JEE_MAINS",         7, None, None, 90.8),
    ("STU1134","Isha Deol",           "isha.d",       "BTECH-CIVIL",  "MGMT", "MANAGEMENT",        8, None, None, "Cat-B"),
    ("STU1135","Jagmohan Lal",        "jagmohan.l",   "BTECH-CIVIL",  "GEN",  "VSAT",              3, None, None, 220),
    ("STU1136","Kamala Devi",         "kamala.d",     "BTECH-CIVIL",  "ST",   "RESERVED_CATEGORY", 4, None, None, "ST Tribal Welfare"),
    ("STU1137","Laxman Singh",        "laxman.s",     "BTECH-CIVIL",  "GEN",  "EAMCET",            5, None, None, 9800),
    ("STU1138","Malati Bai",          "malati.b",     "BTECH-CIVIL",  "SC",   "RESERVED_CATEGORY", 6, None, None, "SC Welfare"),
    ("STU1139","Nayan Tara",          "nayan.t",      "BTECH-CIVIL",  "GEN",  "SPECIAL_STATE",     2, None, None, "Mizoram"),
    ("STU1140","Omveer Singh",        "omveer.s",     "BTECH-CIVIL",  "OBC",  "EAMCET",            1, None, None, 11700),

    # ── B.Tech IT (20 students) ───────────────────────────────────────────────
    ("STU1141","Prakash Jha",         "prakash.j",    "BTECH-IT",     "GEN",  "JEE_MAINS",         1, None, None, 96.7),
    ("STU1142","Rashmi Mishra",       "rashmi.m",     "BTECH-IT",     "GEN",  "VSAT",              1, None, None, 62),
    ("STU1143","Shankar Pillai",      "shankar.p",    "BTECH-IT",     "OBC",  "RESERVED_CATEGORY", 2, None, None, "OBC Concession"),
    ("STU1144","Tanisha Reddy",       "tanisha.r",    "BTECH-IT",     "GEN",  "JEE_MAINS",         2, None, None, 95.3),
    ("STU1145","Udayan Saha",         "udayan.s",     "BTECH-IT",     "SC",   "RESERVED_CATEGORY", 3, None, None, "SC Welfare"),
    ("STU1146","Vani Sharma",         "vani.s",       "BTECH-IT",     "GEN",  "EAMCET",            3, None, None, 5400),
    ("STU1147","Wajid Khan",          "wajid.k",      "BTECH-IT",     "OBC",  "EAMCET",            4, None, None, 8800),
    ("STU1148","Xenia D'Costa",       "xenia.d",      "BTECH-IT",     "GEN",  "JEE_MAINS",         4, None, None, 97.8),
    ("STU1149","Yuvaraj Singh",       "yuvaraj.s",    "BTECH-IT",     "GEN",  "SPECIAL_STATE",     1, None, None, "Jammu & Kashmir"),
    ("STU1150","Zinnia Bose",         "zinnia.b",     "BTECH-IT",     "GEN",  "VSAT",              2, None, None, 175),
    ("STU1151","Ankit Rawat",         "ankit.r",      "BTECH-IT",     "GEN",  "EAMCET",            1, None, None, 6200),
    ("STU1152","Brinda Pillai",       "brinda.p",     "BTECH-IT",     "SC",   "RESERVED_CATEGORY", 3, None, None, "SC Welfare"),
    ("STU1153","Chirag Gupta",        "chirag.g",     "BTECH-IT",     "GEN",  "JEE_MAINS",         4, None, None, 92.1),
    ("STU1154","Drishya Nair",        "drishya.n",    "BTECH-IT",     "GEN",  "SPECIAL_STATE",     2, None, None, "Sikkim"),
    ("STU1155","Elan Chezhian",       "elan.c",       "BTECH-IT",     "OBC",  "EAMCET",            1, None, None, 9400),
    ("STU1156","Fatima Nazir",        "fatima.n",     "BTECH-IT",     "OBC",  "RESERVED_CATEGORY", 3, None, None, "OBC Concession"),
    ("STU1157","Gokul Krishna",       "gokul.k",      "BTECH-IT",     "GEN",  "VSAT",              4, None, None, 260),
    ("STU1158","Hansika Motwani",     "hansika.m",    "BTECH-IT",     "GEN",  "EAMCET",            1, None, None, 7100),
    ("STU1159","Imran Khan",          "imran.k",      "BTECH-IT",     "OBC",  "EAMCET",            2, None, None, 10300),
    ("STU1160","Jayalakshmi S",       "jayalakshmi.s","BTECH-IT",     "SC",   "RESERVED_CATEGORY", 3, None, None, "SC Welfare"),

    # ── BCA (15 students) ─────────────────────────────────────────────────────
    ("STU1161","Keerthi Suresh",      "keerthi.s",    "BCA",          "GEN",  "VSAT",              1, None, None, 78),
    ("STU1162","Lenin Kumar",         "lenin.k",      "BCA",          "OBC",  "RESERVED_CATEGORY", 1, None, None, "OBC Concession"),
    ("STU1163","Megha Rani",          "megha.r",      "BCA",          "GEN",  "JEE_MAINS",         2, None, None, 95.5),
    ("STU1164","Nikhil Reddy",        "nikhil.r",     "BCA",          "GEN",  "EAMCET",            2, None, None, 7800),
    ("STU1165","Oinam Devi",          "oinam.d",      "BCA",          "ST",   "SPECIAL_STATE",     3, None, None, "Manipur"),
    ("STU1166","Prabhu Deva",         "prabhu.d",     "BCA",          "GEN",  "VSAT",              3, None, None, 180),
    ("STU1167","Qurratul Ain",        "qurratul.a",   "BCA",          "OBC",  "EAMCET",            4, None, None, 11000),
    ("STU1168","Reshma Shaikh",       "reshma.s",     "BCA",          "GEN",  "SPECIAL_STATE",     4, None, None, "Jammu & Kashmir"),
    ("STU1169","Supriya Joshi",       "supriya.j",    "BCA",          "SC",   "RESERVED_CATEGORY", 1, None, None, "SC Welfare"),
    ("STU1170","Thiru Kumar",         "thiru.k",      "BCA",          "GEN",  "EAMCET",            2, None, None, 8400),
    ("STU1171","Urvashi Rautela",     "urvashi.r",    "BCA",          "GEN",  "JEE_MAINS",         3, None, None, 91.2),
    ("STU1172","Vivek Oberoi",        "vivek.o",      "BCA",          "OBC",  "RESERVED_CATEGORY", 4, None, None, "OBC Concession"),
    ("STU1173","Waheeda Rehman",      "waheeda.r",    "BCA",          "GEN",  "EAMCET",            1, None, None, 9200),
    ("STU1174","Yashashri Masurkar",  "yashashri.m",  "BCA",          "GEN",  "VSAT",              2, None, None, 340),
    ("STU1175","Zubair Ahmad",        "zubair.a",     "BCA",          "OBC",  "SPECIAL_STATE",     3, None, None, "Ladakh"),

    # ── M.Tech CSE (10 students) ──────────────────────────────────────────────
    ("STU1176","Aarav Mehta",         "aarav.m",      "MTECH-CSE",    "GEN",  "JEE_MAINS",         1, None, None, 96.4),
    ("STU1177","Banu Priya",          "banu.p",       "MTECH-CSE",    "OBC",  "VSAT",              1, None, None, 85),
    ("STU1178","Chandan Mishra",      "chandan.m",    "MTECH-CSE",    "GEN",  "JEE_MAINS",         2, None, None, 95.0),
    ("STU1179","Darshana Rao",        "darshana.r",   "MTECH-CSE",    "SC",   "RESERVED_CATEGORY", 2, None, None, "SC Welfare"),
    ("STU1180","Eknath Pawar",        "eknath.p",     "MTECH-CSE",    "GEN",  "SPECIAL_STATE",     3, None, None, "Assam"),
    ("STU1181","Falguni Pathak",      "falguni.p",    "MTECH-CSE",    "GEN",  "VSAT",              3, None, None, 210),
    ("STU1182","Gopinath Pillai",     "gopinath.p",   "MTECH-CSE",    "GEN",  "JEE_MAINS",         4, None, None, 98.7),
    ("STU1183","Himadri Saha",        "himadri.s",    "MTECH-CSE",    "OBC",  "RESERVED_CATEGORY", 4, None, None, "OBC Concession"),
    ("STU1184","Ishan Khattar",       "ishan.k",      "MTECH-CSE",    "GEN",  "EAMCET",            1, None, None, 4200),
    ("STU1185","Janvi Kapoor",        "janvi.k",      "MTECH-CSE",    "GEN",  "EAMCET",            2, None, None, 5800),

    # ── MBA (10 students) ─────────────────────────────────────────────────────
    ("STU1186","Kinjal Dave",         "kinjal.d",     "MBA",          "GEN",  "VSAT",              1, None, None, 45),
    ("STU1187","Lijo Jose",           "lijo.j",       "MBA",          "OBC",  "RESERVED_CATEGORY", 1, None, None, "OBC Concession"),
    ("STU1188","Malavika Mohanan",    "malavika.m",   "MBA",          "GEN",  "SPECIAL_STATE",     2, None, None, "Jammu & Kashmir"),
    ("STU1189","Nivin Pauly",         "nivin.p",      "MBA",          "GEN",  "MANAGEMENT",        2, None, None, "Cat-B"),
    ("STU1190","Oshin Rawat",         "oshin.r",      "MBA",          "SC",   "RESERVED_CATEGORY", 3, None, None, "SC Welfare"),
    ("STU1191","Prateik Babbar",      "prateik.b",    "MBA",          "GEN",  "VSAT",              3, None, None, 190),
    ("STU1192","Qasida Merchant",     "qasida.m",     "MBA",          "OBC",  "EAMCET",            4, None, None, 6800),
    ("STU1193","Ritesh Deshmukh",     "ritesh.d",     "MBA",          "GEN",  "MANAGEMENT",        4, None, None, "Cat-B"),
    ("STU1194","Swara Bhaskar",       "swara.b",      "MBA",          "GEN",  "SPECIAL_STATE",     1, None, None, "Sikkim"),
    ("STU1195","Tovino Thomas",       "tovino.t",     "MBA",          "GEN",  "MANAGEMENT",        2, None, None, "Cat-B"),

    # ── MCA (5 students) ──────────────────────────────────────────────────────
    ("STU1196","Unni Mukundan",       "unni.m",       "MCA",          "GEN",  "VSAT",              1, None, None, 55),
    ("STU1197","Vidya Balan",         "vidya.b",      "MCA",          "GEN",  "JEE_MAINS",         2, None, None, 95.6),
    ("STU1198","Warina Hussain",      "warina.h",     "MCA",          "OBC",  "RESERVED_CATEGORY", 3, None, None, "OBC Concession"),
    ("STU1199","Yami Gautam",         "yami.g",       "MCA",          "GEN",  "SPECIAL_STATE",     4, None, None, "Jammu & Kashmir"),
    ("STU1200","Zayed Khan",          "zayed.k",      "MCA",          "GEN",  "EAMCET",            2, None, None, 6900),
]
# fmt: on
